applications:
  flask:
    source:
      root: /
    type: "python:3.12"

    dependencies:
      python3:
        pip: "*"

    hooks:
      build: |
        set -eux
        pip install -r requirements.txt

    web:
      commands:
        start: "gunicorn -w 2 -b localhost:$PORT app:app"
      locations:
        "/":
          passthru: true

tasks:
  agent:
    source:
      root: /agent
    type: "python:3.12"

    dependencies:
      python3:
        pip: "*"

    hooks:
      build: |
        set -eux
        pip install -r requirements.txt

    run:
      command: "python run.py"
      timeout: 900

    mounts:
      "/tmp":
        source: "tmp"

routes:
  "https://{default}/":
    type: upstream
    upstream: "flask:http"
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
